- id: docformatter-venv
  name: docformatter-venv
  description: Formats docstrings to follow PEP 257
  entry: docformatter
  language: python
  language_version: python3
  files: \.py$
  args: [--in-place, --wrap-summaries=115, --wrap-descriptions=120]